### ISSUE TITLE
Forslag til UI

### ISSUE THREAD

**Issue by mads-mikkel** [AspIT-CV/Northwind#1]
Der skal tegnes et forslag til brugerfladen. SCRUM master skal godkende det, inden UI implementeres.

**Comment by Jens7388** [comment]
![Udklip](https://user-images.githubusercontent.com/59821392/92573670-6909a280-f286-11ea-911a-22e0a8598ecc.PNG)

**Comment by mads-mikkel** [comment]
Anvend TabControl i stedet for UserControls. TabControlenes content skal dog være en UC.
