### ISSUE TITLE
Lav en back-end server

### ISSUE THREAD

**Issue by mads-mikkel** [AspIT-CV/Northwind#3]
Der skal opsættes en fysisk maskine i lokalet, som klienterne (de .exe der debugges i VS på de andres PC'er) kan tilgå.

**Comment by mads-mikkel** [comment]
[Northwind.sql](https://intranet.aspit.dk/Fagets_Univers/Softwarekonstruktion/_layouts/15/guestaccess.aspx?guestaccesstoken=0QCxVzdQOlq4P6LXEHVHsxATpre95lV2cFKHG3wJflw%3d&docid=2_14ca2221a5dc848518e5dbc343421c5f0&rev=1)

**Comment by chri37i7** [comment]
Skiftet API VM virtuel switch i Hyper-V til en ekstern switch, fremfor en intern så den er direkte på den lokale netvært,
så vi kan forbinde til den over LAN.
