### ISSUE TITLE
Opsætning af server

### ISSUE THREAD

**Issue by chri37i7** [AspIT-CV/Northwind#4]
Skal database-serveren være SQL Server 2019, 
eller bare Windows 10 Enterprise med SSMS?

Skal databasen, og API-applikationen køre på seperate OS'er i virtualisering,
eller på den samme maskine?

**Comment by mads-mikkel** [comment]
Der benyttes en AlienWare PC med det forudinstallerede OS. Der laves to VM's med Windows Server 2019 Standard, diise skal fungere som hhv. applikationsserver (API) og databaseserver.
